// Auto-generated type definitions
// Generated by generate-wundergraph-config.js
// Run: node scripts/generate-wundergraph-config.js

export interface PageInfo {
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface WeatherData {
  temperature: number;
  feelsLike?: number;
  humidity?: number;
  windSpeed?: number;
  condition: string;
  icon?: string;
}

export interface getWeatherResponse {
  location?: Record<string, any>;
  current: WeatherData;
  updatedAt: string;
}

export interface getWeatherForecastResponse {
  location: Record<string, any>;
  forecast: any[];
}

export interface getLaunchesResponse {
  data: any[];
  pageInfo: PageInfo;
}

export interface getUserProfileResponse {
  id: string;
  username: string;
  email: string;
  avatar?: string;
  bio?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface createUserResponse {
  id: string;
  username: string;
  email: string;
  createdAt: string;
}

export interface updateUserResponse {
}

export interface deleteUserResponse {
  success: boolean;
  message?: string;
}

export interface getStatsResponse {
  period: string;
  pageViews: number;
  uniqueVisitors: number;
  avgSessionDuration?: number;
  bounceRate?: number;
  topPages?: any[];
}

export interface submitContactFormResponse {
  success: boolean;
  ticketId: string;
  message?: string;
}
