// Auto-generated WunderGraph configuration
// Generated by generate-wundergraph-config.js
// Run: node scripts/generate-wundergraph-config.js

import { configureWunderGraphApplication, introspect } from '@wundergraph/sdk';

// REST API data sources (converted to GraphQL via OpenAPI)
const api = introspect.openApi({
  apiNamespace: 'api',
  source: {
    kind: 'file',
    filePath: '../api-config.yaml',
  },
});

// GraphQL API data sources
const get_launches = introspect.graphql({
  apiNamespace: 'getLaunches',
  url: 'https://api.example.com/graphql', // TODO: Configure actual URL
});

configureWunderGraphApplication({
  apis: [
    api,
    get_launches,
  ],
  server: {
    port: 9991,
    playground: true,
  },
  codeGenerators: [
    {
      path: './operations',
      openapi: {
        outputDir: './generated/openapi',
      },
    },
  ],
});